// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdURhve8UdtEbk_b_WmNt6RjMpc0fxMnU',
    appId: '1:404846467635:web:4f3ca8669f02563e83a146',
    messagingSenderId: '404846467635',
    projectId: 'athlosight3',
    authDomain: 'athlosight3.firebaseapp.com',
    databaseURL: 'https://athlosight3-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'athlosight3.appspot.com',
    measurementId: 'G-DRKP1E64TC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhQbzavOoog6SKEROQdRgMLUTSXFZfJNI',
    appId: '1:404846467635:android:cfa730a76f948f3c83a146',
    messagingSenderId: '404846467635',
    projectId: 'athlosight3',
    databaseURL: 'https://athlosight3-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'athlosight3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgpwpMlYbLL-S4S8jHdOfca_zSG2YzIl8',
    appId: '1:404846467635:ios:0e5c409162411eb183a146',
    messagingSenderId: '404846467635',
    projectId: 'athlosight3',
    databaseURL: 'https://athlosight3-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'athlosight3.appspot.com',
    androidClientId: '404846467635-0t1ksdh85r82v97pkds7a46ge2ffssis.apps.googleusercontent.com',
    iosClientId: '404846467635-45dpopu0uaj45g0fks9h00ilps8rp66k.apps.googleusercontent.com',
    iosBundleId: 'com.athlosight.pbl',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgpwpMlYbLL-S4S8jHdOfca_zSG2YzIl8',
    appId: '1:404846467635:ios:e29b63fa9510faa783a146',
    messagingSenderId: '404846467635',
    projectId: 'athlosight3',
    databaseURL: 'https://athlosight3-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'athlosight3.appspot.com',
    androidClientId: '404846467635-0t1ksdh85r82v97pkds7a46ge2ffssis.apps.googleusercontent.com',
    iosClientId: '404846467635-v7ptpgirls233p5pcvh7eo6911roq508.apps.googleusercontent.com',
    iosBundleId: 'com.athlosight.pbl.RunnerTests',
  );
}
